
[http]
  [http.routers]
    [http.routers.qlmuxproxy-127]
      rule = "Host(`127.0.0.1`)"
      entryPoints = ["web", "websecure"]
      service = "qlmuxproxy-127-service"

    [http.routers.qlmuxproxy-external]
      rule = "Host(`qlmuxproxy.wimsey.dev`)"
      entryPoints = ["web", "websecure"]
      service = "qlmuxproxy-127-service"
      [http.routers.qlmuxproxy-external.tls]
        certResolver = "myresolver"


  [http.services]
    [http.services.qlmuxproxy-127-service.loadBalancer]
      [[http.services.qlmuxproxy-127-service.loadBalancer.servers]]
        url = "http://localhost:9180"


