
[http]
  [http.routers]
    [http.routers.qlmuxproxy]
      rule = "Host(`qlmuxproxy.wimsey.dev`)"
      entryPoints = ["web", "websecure"]
      service = "qlmuxproxy-service"
      [http.routers.qlmuxproxy.tls]
        certResolver = "myresolver"

  [http.services]
    [http.services.qlmuxproxy-service.loadBalancer]
      [[http.services.qlmuxproxy-service.loadBalancer.servers]]
        url = "http://localhost:9180"


