
[http]
  [http.routers]
    [http.routers.racedb]
      rule = "Host(`racedb.wimsey.dev`)"
      entryPoints = ["web", "websecure"]
      service = "racedb-service"
      [http.routers.racedb.tls]
        certResolver = "myresolver"

  [http.services]
    [http.services.racedb-service.loadBalancer]
      [[http.services.racedb-service.loadBalancer.servers]]
        url = "http://localhost:9080"
