[log]
  level = "INFO"

[api]
  insecure = true

[accessLog]
  [accessLog.fields.names]
    StartUTC = "drop"
  filePath = "/logs/access.log"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.myresolver.acme]
    caServer = "https://acme-v02.api.letsencrypt.org/directory"
    email = "stuart.lynne@gmail.com"
    storage = "/letsencrypt/acme.json"
    # See provider.env to set the credentials. These must be set in the environment
    # and are specific to the provider you are using and specify below.
    # See also: https://doc.traefik.io/traefik/v1.7/configuration/acme/#provider
    [certificatesResolvers.myresolver.acme.dnsChallenge]
      provider = "namecheap"    # namecheap, cloudflare, route53, etc
      disablePropagationCheck = true
      delayBeforeCheck = 90
      resolvers = ["1.1.1.1:53", "8.8.8.8:53"]


[providers]
  [providers.docker]
    exposedByDefault = true
  [providers.file]
    directory = "/dynamic"

